// Public Constants

// This public constant represents...
const <PublicPackageConstantName> = <publicPackageConstantValue>
...

// Private Constants

// This private constant represents...
const <privatePackageConstantName> = <privatePackageConstantValue>
...
