// PACKAGE FUNCTIONS

// Public Functions

// This function returns...
func <PackageFunctionName>(<arguments>) <ResultType> {
	var <result> <ResultType>
	...
	return <result>
}
...

// Private Functions

// This private function returns...
func <privatePackageFunctionName>(<arguments>) <ResultType> {
	var <result> <ResultType>
	...
	return <result>
}
...
// This function returns...
func <FunctionName>(<arguments>) <resultType> {
	var <result> <resultType>
	...
	return <result>
}
...
