// This function returns...
func <FunctionName>(<arguments>) <resultType> {
	var <result> <resultType>
	...
	return <result>
}
...

// This private function returns...
func <privateFunctionName>(<arguments>) <resultType> {
	var <result> <resultType>
	...
	return <result>
}
...
