// Public Functions

// This public function returns...
func <PublicPackageFunctionName>(<arguments>) <AbstractType> {
	var <result> <AbstractType>
	...
	return <result>
}
...

// Private Functions

// This private function returns...
func <privatePackageFunctionName>(<arguments>) <ResultType> {
	var <result> <ResultType>
	...
	return <result>
}
...
